title: My Jekyll Blog
description: A modern Jekyll blog with all the essential features.
baseurl: "/anime"
url: "https://ltxstudio.github.io"

markdown: kramdown
theme: "minima"  # You can choose another theme if you prefer

plugins:
  - jekyll-seo-tag   # SEO tag plugin for better search engine optimization
  - jekyll-paginate  # Pagination plugin
  - jekyll-sitemap   # Sitemap plugin
  - jekyll-search    # For search functionality

paginate: 5  # Number of posts per page
paginate_path: "/page:num/"

# Categories configuration (optional)
categories:
  - Technology
  - Design
  - Lifestyle

# Disqus configuration for comments
disqus:
  shortname: "your-disqus-shortname"
